### ISSUE TITLE
Links to Bazel documentation stopped working in blog posts

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel-blog#24]
See https://blog.bazel.build/2016/03/31/autoconfiguration.html for examples (I am afraid it is pervasive in older blog posts as well): 
- since we have moved to blog.bazel.build, all relative links to docs started to point to a file under that hostname instead of bazel.build

**Comment by davidstanke** [comment]
Nice catch. Let's definitely fix asap. I'm still getting up to speed on how these sites are hosted... it looks like the links go to places like /docs/foo.html, but should actually go to //docs.bazel.build/foo.html

I can thing of two possible global fixes:

1. create a redirect on blog.bazel.build: /docs/* --> //docs.bazel.build/$1
2. do a global search-and-replace on the contents of blog.bazel.build

Are either/both of these feasible? (#2 is probably preferable as it doesn't introduce a new redirect). I'm happy to look into it but may not be as fast as others since I'm not yet familiar with how the site is hosted/edited.

I'd obviously prefer not to replace every link one-by-one!

**Comment by michelleirvine** [comment]
on this -- I'll replace the links
